online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace= 'accounts')),
    path('accounts_api/', include('accounts.api_urls', namespace= 'accounts_api')),
    path('shop/', include('shop.urls', namespace= 'shop')),
    path('shop_api/', include('shop.api_urls', namespace= 'shop_api')),
    path('', include('dashboard.urls', namespace= 'home')),
    path('orders/' , include('orders.urls', namespace='orders')),
    path('orders_api/' , include('orders.api_urls', namespace='orders_api')),
    path('api-auth/', include('rest_framework.urls'))
]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT) #برای نشون دادن عکس ها در برنامه

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
   authentication_classes=[],
)

swagger_urls = [
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += swagger_urls

online_shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns=[
    path('create/', views.OrderCreateView.as_view() , name='order_create'),
    path('detail/<int:order_id>/' , views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/' , views.CartView.as_view() , name='cart'),
    path('cart/add/<int:product_id>/' , views.CartAddView.as_view() ,name='addcart'),
    path('cart/remove/<int:product_id>/' , views.RemoveCardView.as_view() , name='cart_remove'),
    # path('checkprofile/' , views.CheckProfileCart.as_view() , name='check'),
    path('apply/<int:order_id>' ,views.CouponApplyView.as_view() , name='apply_coupon'),
    # path('api/', include('orders.api_urls', namespace='api_order')),
    path('pay/<int:order_id>',views.OrderPayView.as_view(),name='order_pay'),
    path('verify_order/', views.VerifyOrderView.as_view(), name='order_verify'),
]

online_shop/shop/urls.py
from django.urls import path , include
from .views import ProductDetailView

app_name='shop'
urlpatterns = [
    path('<slug:slug>/', ProductDetailView.as_view(), name='details'),
]

online_shop/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
# مدل یوزری که فعال است را از داخل تنظیمات میاره برای ما
from shop.models import Product
from django.core.validators import MinValueValidator, MaxValueValidator


class Order(models.Model):
	user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders')
	paid = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	discount = models.IntegerField(blank=True, null=True, default=None) # مقدار تخفیف

	class Meta:
		ordering = ('paid', '-updated')

	def __str__(self):
		return f'{self.user} - {str(self.id)}'

	def get_total_price(self):
		total = sum(item.get_cost() for item in self.items.all())
		if self.discount:
			discount_price = (self.discount / 100) * total
			return int(total - discount_price)
		return total
	

class OrderItem(models.Model):
	order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	price = models.IntegerField()
	quantity = models.IntegerField(default=1)

	def __str__(self):
		return str(self.id)

	def get_cost(self):
		return self.price * self.quantity


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField() # شروع
    valid_to = models.DateTimeField() # انتها
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(90)])
    active = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.code

online_shop/orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)


class CouponApplyForm(forms.Form):
    code = forms.CharField()

online_shop/orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .cart import Cart
from shop.models import Product
from accounts.models import User
from .forms import CartAddForm , CouponApplyForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Order, OrderItem, Coupon
import requests
import json
from django.http import HttpResponse
import datetime
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.conf import settings
# from orders.tasks import send_email_fun
from orders.tasks import send_order_status_email


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'orders/cart.html', {'cart': cart})


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:cart')


class RemoveCardView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')


class OrderDetailView(LoginRequiredMixin, View):
    form_class = CouponApplyForm

    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        return render(request, 'orders/order.html', {'order': order, 'form': self.form_class})


class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        # for item in cart:
        #     quant_store = Product.objects.get(slug=item['product'])
        #     if item['quantity'] > quant_store.quantity:
        #         messages.error(
        #             request, f"Sorry, this {item['product']}is not available in the quantity you requested", 'danger')
        #         return redirect('order:cart')
            
        # برای کاربری که لاگین کرده یک سبد خرید ایجاد میشود :
        order = Order.objects.create(user=request.user)
        for item in cart:
            # quant_store = Product.objects.get(slug=item['product'])
            OrderItem.objects.create(
                order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
        #     quant_store.quantity -= item['quantity']
        #     quant_store.save()

        # cart.clear()
        return redirect('orders:order_detail', order.id)
    

if settings.SANDBOX:
    sandbox = "sandbox"
else:
    sandbox = "www"

ZP_API_REQUEST = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = (
    f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
)
ZP_API_STARTPAY = f"https://{sandbox}.zarinpal.com/pg/StartPay/"
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
CallbackURL = "http://127.0.0.1:8000/orders/verify_order/"


class OrderPayView(View):
    def get(self, request, order_id):
        order = Order.objects.get(id=order_id)
        request.session["order_pay"] = {
            "order_id": order.id,
        }
        data = {
            "MerchantID": settings.MERCHANT,
            "Amount": order.get_total_price(),
            "Description": description,
            "CallbackURL": CallbackURL,
            "metadata": {"mobile": order.user.phone_number},
        }
        data = json.dumps(data)
        headers = {
            "accept": "application/json",
            "content-type": "application/json",
            "content-length": str(len(data)),
        }
        try:
            response = requests.post(
                ZP_API_REQUEST, data=data, headers=headers, timeout=10
            )
            if response.status_code == 200:
                response = response.json()
                if response["Status"] == 100:
                    return redirect(ZP_API_STARTPAY + str(response["Authority"]))
                elif response.get("errors"):
                    e_code = response["errors"]["code"]
                    e_message = response["errors"]["message"]
                    return HttpResponse(
                        f"Error code: {e_code}, Error Message: {e_message}"
                    )
            return HttpResponse(response.items())

        except requests.exceptions.Timeout:
            return {"status": False, "code": "timeout"}
        except requests.exceptions.ConnectionError:
            return {"status": False, "code": "connection error"}


class VerifyOrderView(LoginRequiredMixin, View):
	def get(self, request):
		order_id = request.session['order_pay']['order_id']
		if request.GET.get('Status') == 'OK':
                    user= User.objects.all()
                    cart = Cart(request)
                    cart.clear()
                    to_email = user.email
                    subject = "Order Confirmed Successfuly"
                    message = f"Transaction success order ID: {order_id}"
                    send_order_status_email.delay(to_email ,subject, message)
                    # send_email_fun.delay(subject, message, settings.EMAIL_HOST_USER, to_email)

                    return HttpResponse(f"Transaction success , order ID: {order_id}")
                
		else:
			return HttpResponse('Transaction failed or canceled by user')
                


#******************************
# class CheckProfileCart(LoginRequiredMixin, View):
#     def get(self, request):
#         user = Account.objects.get(id=request.user.id)
#         if request.user.postal_code is not None:
#             return render(request, 'orders/checkprofile.html', {'user': user})
#         return render(request, 'orders/error.html')


class CouponApplyView(LoginRequiredMixin, View):
	form_class = CouponApplyForm

	def post(self, request, order_id):
		now = datetime.datetime.now()
		form = self.form_class(request.POST)
		if form.is_valid():
			code = form.cleaned_data['code']
			try:
				coupon = Coupon.objects.get(code__exact=code, valid_from__lte=now, valid_to__gte=now, active=True)
			except Coupon.DoesNotExist:
				messages.error(request, 'this coupon does not exists', 'danger')
				return redirect('orders:order_detail', order_id)
			order = Order.objects.get(id=order_id)
			order.discount = coupon.discount
			order.save()
		return redirect('orders:order_detail', order_id)

online_shop/orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-dark table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Total Price</th>
        <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.product }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.total_price }}</td>
        <td><a href="{% url 'orders:cart_remove' item.product.id %}">remove</a></td>
    </tr>
    {% endfor %}

    <tr>
        <td>Total</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>

    </tbody>
</table>

<a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>

{% endblock %}

online_shop/orders/templates/orders/order.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="justify-content: center;">
    <div class="card rounded-3 mb-4">
        <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
                <div class="col-md-2 col-lg-2 col-xl-2">
                    <h5 class="mb-0">Checkout : </h5>
                </div>

                <div>
                    <br/>
                    <table class="table table-warning table-striped table-sm">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total Price</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in cart %}
                        <tr>
                            <td>{{ item.product }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.total_price }}</td>
                        </tr>
                        {% endfor %}
                    
                        </tbody>
                    </table>
                </div>

                <div>
                    <br/>
                    <h5 class="mb-0">{{ order.user }} </h5>
                </div>
                <form action="{% url 'orders:apply_coupon' order.id %}" method="post">
                    <br/>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Apply">
                </form>
                <div>
                    <br/>
                    <div class="col-md-3 col-lg-3 col-xl-3">
                        <h5 class="mb-0">Total Price : {{order.get_total_price}}</h5>
                    </div>
                    <a href="{% url 'orders:order_pay' order.id %}" class="btn btn-primary">Pay</a>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}