online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace= 'accounts')),
    path('accounts_api/', include('accounts.api_urls', namespace= 'accounts_api')),
    path('shop/', include('shop.urls', namespace= 'shop')),
    path('shop_api/', include('shop.api_urls', namespace= 'shop_api')),
    path('', include('dashboard.urls', namespace= 'home')),
    path('orders/' , include('orders.urls', namespace='orders')),
    path('orders_api/' , include('orders.api_urls', namespace='orders_api')),
    path('api-auth/', include('rest_framework.urls'))
]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT) #برای نشون دادن عکس ها در برنامه

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
   authentication_classes=[],
)

swagger_urls = [
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += swagger_urls

online_shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns=[
    path('create/', views.OrderCreateView.as_view() , name='order_create'),
    path('detail/<int:order_id>/' , views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/' , views.CartView.as_view() , name='cart'),
    path('cart/add/<int:product_id>/' , views.CartAddView.as_view() ,name='addcart'),
    path('cart/remove/<int:product_id>/' , views.RemoveCardView.as_view() , name='cart_remove'),
    # path('checkprofile/' , views.CheckProfileCart.as_view() , name='check'),
    path('apply/<int:order_id>' ,views.CouponApplyView.as_view() , name='apply_coupon'),
    # path('api/', include('orders.api_urls', namespace='api_order')),
    path('pay/<int:order_id>',views.OrderPayView.as_view(),name='order_pay'),
    path('verify_order/', views.VerifyOrderView.as_view(), name='order_verify'),
]

online_shop/shop/urls.py
from django.urls import path , include
from .views import ProductDetailView

app_name='shop'
urlpatterns = [
    path('<slug:slug>/', ProductDetailView.as_view(), name='details'),
]

online_shop/shop/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from core.models import BaseModel



class Category(models.Model):
    title = models.CharField(max_length=200)
    sub_category = models.ForeignKey(
        'self', on_delete=models.CASCADE,
        related_name='scategory', null=True, blank=True
    )
    is_sub = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering= ('title',)
        # برای درست نوشتن مدل جمعه اسم
        verbose_name= 'category' #مفرد
        verbose_name_plural= 'caregories' #جمع

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('dashboard:category_filter', args={self.slug})

    def save(self, *args, **kwargs): # new
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)



class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    image = models.ImageField(upload_to='products/%Y/%m/%d')
    title = models.CharField(max_length=250)
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now= True)
    slug = models.SlugField(unique=True)
    quantity = models.PositiveIntegerField()
    count_buying = models.PositiveIntegerField()
    rate = models.PositiveIntegerField()

    class Meta:
        ordering = ('title',)

    def __str__(self) -> str:
        return self.title
        
    def get_absolute_url(self):
        return reverse('shop:details', args=[self.slug])

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     return super().save(*args, **kwargs)

online_shop/shop/views.py
from django.shortcuts import render
from django.views import View
from django.shortcuts import get_object_or_404
from .models import Product
from orders.forms import CartAddForm


class ProductDetailView(View):
    def get(self, request, slug):
        product = Product.objects.get(slug = slug)
        form = CartAddForm()
        return render(request, 'shop/detail.html', {'product': product , 'form': form})

online_shop/shop/templates/shop/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container my-5">
    <div class="row justify-content-center align-items-center">
      <div class="col-md-6">
        <div class="card">
          <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
        </div>
      </div>
      <div class="col-md-6 p-5" style="background-color: #f9f9f9;">
        <h2 class="card-title">{{ product.title }}</h2>
        <hr style="border-top: 2px solid orange; margin-bottom: 1rem;">
        <p class="card-text">{{ product.description|safe }}</p>
        <h3 class="card-price text-warning">{{ product.price }} Toman</h3>
        <form action="{% url 'orders:addcart' product.id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="col-12 col-lg-12 add_to" value="add to cart">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

online_shop/shop/templates/shop/product.html
<div class="row m-2">

    {% for product in products %}
    <div class="col-md-3">
        <div class="card mb-3">
            <img src="{{product.image.url}}" class="card-img-top" style="height:200px;">
            <div class="card-body">
                <h5 class="card-title">{{product.title}}</h5>
                <p class="card-text">{{product.price}} Hezar toman</p>
                <a href="{{ product.get_absolute_url }}" class="btn btn-warning">Detail</a>
            </div>
        </div>
    </div>
    {% endfor %}
    <form>
      {{ search_form }}
      <input type="submit" value="search" class="nav-item">
    </form>
    <br\><br/><br>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if product.has_previous %} 
            <li class="page-item"><a class="page-link" href="?page=1">First</a></li> 
          <li class="page-item"><a class="page-link" href="?page={{ product.previous_page_number}}">{{ product.previous_page_number}}</a></li>
            {% endif %}

          <li class="page-item"><a class="page-link" href="?page={{ product.number}}" style="background-color:rgb(234, 201, 55)
        ">{{ product.number}}</a></li>

          {% if product.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ product.next_page_number }}">{{ product.next_page_number }}</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ product.paginator.num_pages }}">Last</a></li>
          {% endif %}
        </ul>
      </nav>

</div>