online_shop/accounts/urls.py
from django.urls import path
from . import views
from .views import ProfileView

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/' , ProfileView.as_view() , name='profile'),
]

online_shop/dashboard/urls.py
from django.urls import path
from . import views

app_name= 'dashboard'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter')
]

online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace= 'accounts')),
    path('accounts_api/', include('accounts.api_urls', namespace= 'accounts_api')),
    path('shop/', include('shop.urls', namespace= 'shop')),
    path('shop_api/', include('shop.api_urls', namespace= 'shop_api')),
    path('', include('dashboard.urls', namespace= 'home')),
    path('orders/' , include('orders.urls', namespace='orders')),
    path('orders_api/' , include('orders.api_urls', namespace='orders_api')),
    path('api-auth/', include('rest_framework.urls'))
]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT) #برای نشون دادن عکس ها در برنامه

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
   authentication_classes=[],
)

swagger_urls = [
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += swagger_urls

online_shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns=[
    path('create/', views.OrderCreateView.as_view() , name='order_create'),
    path('detail/<int:order_id>/' , views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/' , views.CartView.as_view() , name='cart'),
    path('cart/add/<int:product_id>/' , views.CartAddView.as_view() ,name='addcart'),
    path('cart/remove/<int:product_id>/' , views.RemoveCardView.as_view() , name='cart_remove'),
    # path('checkprofile/' , views.CheckProfileCart.as_view() , name='check'),
    path('apply/<int:order_id>' ,views.CouponApplyView.as_view() , name='apply_coupon'),
    # path('api/', include('orders.api_urls', namespace='api_order')),
    path('pay/<int:order_id>',views.OrderPayView.as_view(),name='order_pay'),
    path('verify_order/', views.VerifyOrderView.as_view(), name='order_verify'),
]

online_shop/shop/urls.py
from django.urls import path , include
from .views import ProductDetailView

app_name='shop'
urlpatterns = [
    path('<slug:slug>/', ProductDetailView.as_view(), name='details'),
]

online_shop/templates/inc/footer.html
  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              Contact Us
            </h4>
            <div class="contact_link_box">
              <a href="https://goo.gl/maps/HTrc35Hpzrodi61J7"  target="_blank" >
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  mashhad, ladan street
                </span>
              </a><br>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call 09052966415
                </span>
              </a><br>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  as.faraso.97@gmail.com
                </span><br>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              {{info.title}}
            </a>
            <p>
Join us in SocialMedia and make us better and the Best            </p>
            <div class="footer_social">
              <svg class="share" style="width:24px;height:24px" viewBox="0 0 24 24">
                <path d="M18,16.08C17.24,16.08 16.56,16.38 16.04,16.85L8.91,12.7C8.96,12.47 9,12.24 9,12C9,11.76 8.96,11.53 8.91,11.3L15.96,7.19C16.5,7.69 17.21,8 18,8A3,3 0 0,0 21,5A3,3 0 0,0 18,2A3,3 0 0,0 15,5C15,5.24 15.04,5.47 15.09,5.7L8.04,9.81C7.5,9.31 6.79,9 6,9A3,3 0 0,0 3,12A3,3 0 0,0 6,15C6.79,15 7.5,14.69 8.04,14.19L15.16,18.34C15.11,18.55 15.08,18.77 15.08,19C15.08,20.61 16.39,21.91 18,21.91C19.61,21.91 20.92,20.61 20.92,19A2.92,2.92 0 0,0 18,16.08Z" /></svg>
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                <path d="M17,2V2H17V6H15C14.31,6 14,6.81 14,7.5V10H14L17,10V14H14V22H10V14H7V10H10V6A4,4 0 0,1 14,2H17Z" /></svg>
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                <path  d="M22.46,6C21.69,6.35 20.86,6.58 20,6.69C20.88,6.16 21.56,5.32 21.88,4.31C21.05,4.81 20.13,5.16 19.16,5.36C18.37,4.5 17.26,4 16,4C13.65,4 11.73,5.92 11.73,8.29C11.73,8.63 11.77,8.96 11.84,9.27C8.28,9.09 5.11,7.38 3,4.79C2.63,5.42 2.42,6.16 2.42,6.94C2.42,8.43 3.17,9.75 4.33,10.5C3.62,10.5 2.96,10.3 2.38,10C2.38,10 2.38,10 2.38,10.03C2.38,12.11 3.86,13.85 5.82,14.24C5.46,14.34 5.08,14.39 4.69,14.39C4.42,14.39 4.15,14.36 3.89,14.31C4.43,16 6,17.26 7.89,17.29C6.43,18.45 4.58,19.13 2.56,19.13C2.22,19.13 1.88,19.11 1.54,19.07C3.44,20.29 5.7,21 8.12,21C16,21 20.33,14.46 20.33,8.79C20.33,8.6 20.33,8.42 20.32,8.23C21.16,7.63 21.88,6.87 22.46,6Z" /></svg>
               <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                <path  d="M7.8,2H16.2C19.4,2 22,4.6 22,7.8V16.2A5.8,5.8 0 0,1 16.2,22H7.8C4.6,22 2,19.4 2,16.2V7.8A5.8,5.8 0 0,1 7.8,2M7.6,4A3.6,3.6 0 0,0 4,7.6V16.4C4,18.39 5.61,20 7.6,20H16.4A3.6,3.6 0 0,0 20,16.4V7.6C20,5.61 18.39,4 16.4,4H7.6M17.25,5.5A1.25,1.25 0 0,1 18.5,6.75A1.25,1.25 0 0,1 17.25,8A1.25,1.25 0 0,1 16,6.75A1.25,1.25 0 0,1 17.25,5.5M12,7A5,5 0 0,1 17,12A5,5 0 0,1 12,17A5,5 0 0,1 7,12A5,5 0 0,1 12,7M12,9A3,3 0 0,0 9,12A3,3 0 0,0 12,15A3,3 0 0,0 15,12A3,3 0 0,0 12,9Z" /></svg>            
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Opening Hours
          </h4>
          <p>
            Everyday
          </p>
          <p>
            {{info.opening_hours}}
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Maktab-93 {{info.title}}</a><br><br>
          &copy; <span id="displayYear"></span> Distributed By kiana alamy
        </p>
      </div>
    </div>


      

  </footer>
  <!-- footer section -->

online_shop/templates/inc/message.html
{% if messages%}
    {% for msg in messages%}
        <p class = "alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}
{% endif %}

online_shop/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
            <a class="nav-link active" href="{% url 'accounts:register' %}">Register</a>
            <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
            </li>
            <a class="nav-link" href="{% url 'accounts:profile' request.user.id %}"><svg
                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-person-bounding-box" viewBox="0 0 16 16">
                <path
                    d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z" />
                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
            </svg> Profile</a>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'orders:cart' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16"
                        height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                        <path
                            d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
                    </svg> Cart {{cart|length}}</a>
            </li>

        </div>
    </div>
</nav>